export const SCREEN_RESPONSES = {
  SEL_MENU: {
    screen: "SEL_MENU",
    data: {
      chk_trad_sp: false,
      chk_trad_cp: false,
      chk_carn_pollo_sp: false,
      chk_carn_pollo_cp: false,
      chk_carn_tocin_sp: false,
      chk_carn_tocin_cp: false,
      chk_esp_sp: false,
      chk_esp_cp: false,
      chk_sl_pollo_sp: false,
      chk_sl_pollo_cp: false,
      chk_d_carn_sp: false,
      chk_d_carn_cp: false,
      chk_d_carn_pollo_sp: false,
      chk_d_carn_pollo_cp: false,
      chk_d_carn_tocin_sp: false,
      chk_d_carn_tocin_cp: false,
      chk_d_esp_sp: false,
      chk_d_esp_cp: false,
      chk_pe_trad_sp: false,
      chk_pe_trad_cp: false,
      chk_pe_pollo_sp: false,
      chk_pe_pollo_cp: false,
      chk_pe_tocin_sp: false,
      chk_pe_tocin_cp: false,
      chk_pe_esp_sp: false,
      chk_pe_esp_cp: false,
      chk_pa_xl: false,
      chk_salchi_xl: false,
      chk_chori_xl: false,
      chk_pa_locas: false,
    },
  },

  CANTIDADES: {
    screen: "CANTIDADES",
    data: {
      chk_trad_sp: false,
      chk_trad_cp: false,
      chk_carn_pollo_sp: false,
      chk_carn_pollo_cp: false,
      chk_carn_tocin_sp: false,
      chk_carn_tocin_cp: false,
      chk_esp_sp: false,
      chk_esp_cp: false,
      chk_sl_pollo_sp: false,
      chk_sl_pollo_cp: false,
      chk_d_carn_sp: false,
      chk_d_carn_cp: false,
      chk_d_carn_pollo_sp: false,
      chk_d_carn_pollo_cp: false,
      chk_d_carn_tocin_sp: false,
      chk_d_carn_tocin_cp: false,
      chk_d_esp_sp: false,
      chk_d_esp_cp: false,
      chk_pe_trad_sp: false,
      chk_pe_trad_cp: false,
      chk_pe_pollo_sp: false,
      chk_pe_pollo_cp: false,
      chk_pe_tocin_sp: false,
      chk_pe_tocin_cp: false,
      chk_pe_esp_sp: false,
      chk_pe_esp_cp: false,
      chk_pa_xl: false,
      chk_salchi_xl: false,
      chk_chori_xl: false,
      chk_pa_locas: false,
    },
  },

  ADICIONALES: {
    screen: "ADICIONALES",
    data: {
      chk_ad_tocin: false,
      chk_ad_queso: false,
      chk_ad_chorizo: false,
      chk_ad_pollo: false,
      chk_ad_salchi: false,
      chk_ad_carn_ham: false,
      chk_obs_adicionales: false,
    },
  },

  BEBIDAS: {
    screen: "BEBIDAS",
    data: {
      chk_gas_mzn: false,
      chk_gas_pepsi: false,
      chk_gas_kola: false,
      chk_gas_colombiana: false,
      chk_gas_uva: false,
      chk_hit_tropical: false,
      chk_hit_mango: false,
      chk_hit_mora: false,
      chk_mr_tea: false,
      chk_agua_sn_gas: false,
      chk_agua_cn_gas: false,
      chk_h2o_pet: false,
    },
  },

  FINAL: {
    screen: "FINAL",
    data: {},
  },

  MET_ENTREGA: {
    screen: "MET_ENTREGA",
    data: {},
  },

  SUCCESS: {
    screen: "SUCCESS",
    data: {
      extension_message_response: {
        params: {
          flow_token: "REPLACE_FLOW_TOKEN",
          some_param_name: "PASS_CUSTOM_VALUE",
        },
      },
    },
  },
};
